version: '2'
services:
    mywedding-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/MyWedding/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=MyWedding
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
